### ISSUE TITLE
No valid websocket ethereum nodes found

### ISSUE THREAD

**Issue by q3579t** [almindor/etherwall#118] opened 2020-04-26 08:34 UTC
I am getting the following error when launching Etherwall as thin client:
"No valid websocket ethereum nodes found".
This happens regardless of Etherwall version and PC used.
Etherwall was connecting smoothly few weeks ago.
Is there some problem currently going on with the remote server?
It would be nice to let users change the remote server address directly from the interface.

**Comment by almindor** [comment] 2020-04-26 15:19
Yes, the server ran out of disk space I'm afraid. This will take a bit to fix, I'll probably have to force a resync from scratch.

**Comment by almindor** [comment] 2020-04-26 15:27
Requested additional SSD drive for the server, once they add it in I can restart the services. I suspect earliest tomorrow. Sorry for this but going from scratch to make up some free space would take way longer...

**Comment by almindor** [comment] 2020-04-26 18:44
Disk added, node is now syncing back to chain tip, I suspect it'll be fully back by tomorrow. I will remove the warning message once everything is synced up and working right again.

NOTE: I deleted the "history" db to free some space initially which means any transactions not recorded on your local EW instance won't show up until this gets repopulated. I suspect it will take a couple days for that. I also only backfill one month into the past to keep the size under control.

**Comment by q3579t** [comment] 2020-04-30 02:22
Thank you for the prompt action.
Will wait for synchronization to complete, then.

**Comment by almindor** [comment] 2020-04-30 14:25
Sadly it seems the disk-full writes have corrupted parity's blockchain data. It seems to have gotten stuck syncing so I reset it from 0.

I suspect a few days more will be needed :( If you have an urgent request you can use other wallets that can access geth's accounts, see FAQ for more info on that.

**Comment by almindor** [comment] 2020-05-01 00:30
Parity is now synced up, still waiting for the history catchup but you should be able to send transactions and everything else. I will flag server status to green soon.

**Comment by almindor** [comment] 2020-05-01 00:37
I think this is now resolved, please re-open if you're still having issues.

**Comment by AJGierer** [comment] 2020-05-07 13:11
Still having some issues on the OSX app (and looks like the download link is still 2.2.3, not 2.4)
Stuck while saying "Connecting to Node"
Also seeing:
```
HTTP Response parse error: illegal value
Response parse error: illegal value
```

**Comment by almindor** [comment] 2020-05-07 15:09
There was a short window yesterday when the server was down.. but if you're still getting this maybe it's related to some specific query from your side.

I had to upgrade a node.js/postgres library dependency because it broke during the server side upgrade, maybe there's a bug now, I'll keep this open until we can figure it out. Can you paste your full log please? I'd like to see which request fails. You can switch to "debug" for full info.

Download for macOSX should be [this link](https://github.com/almindor/etherwall/releases/download/v2.4.0/macos_etherwall_2_4_0.dmg) which does say v2.4.0 in the url.

**Comment by AJGierer** [comment] 2020-05-07 15:18
2.4 Link worked. Thanks you!
Even with the update I'm getting the same logs in Debug (under "Application" but the "Geth" logs have a lot more going on), so it might be an issue on my side??:
```
Response parse error: illegal value
Response error: unknown error
HTTP Response parse error: illegal value
Response error: unknown error
HTTP Response parse error: illegal value
```
Any thoughts?

**Comment by AJGierer** [comment] 2020-05-07 15:21
Update: Debug updated when I restarted the app:
```
Connected to IPC socket
Connecting to IPC socket /Users/andrewgierer/Library/Ethereum/geth.ipc
Geth starting /Applications/Etherwall.app/Contents/MacOS/geth --syncmode=fast --cache 512 --datadir /Users/andrewgierer/Library/Ethereum --nousb --maxpeers=0 --nodiscover --nat=none
Response error: unknown error
HTTP Response parse error: illegal value
HTTP Post reply: 
Checking to see if there is an already running geth...
Etherwall starting
Response error: unknown error
HTTP Response parse error: illegal value
HTTP Post reply: 
Response parse error: illegal value
HTTP Post reply: 
Connecting to main Etherwall server
HTTP Post request: {
}

HTTP Post request: {
}

HTTP Post request: {
    "currencies": [
        "BTC",
        "EUR",
        "CAD",
        "USD",
        "GBP"
    ],
    "version": 2
}


```

**Comment by almindor** [comment] 2020-05-07 15:28
Ok that seems like the initial currencies and basic connection queries failed. Which is odd because it works fine for me, I just checked (I'm on Linux tho).

I'll have to try this from a mac and debug the connectivity. Do you get the other info (e.g. your accounts etc.) or does it error out and stop?

**Comment by AJGierer** [comment] 2020-05-07 15:30
Errors out and stops there. So I can only access the Settings and Logs tabs (and each of their sub-tabs)
I can see the Geth log if that helps (could DM you that)

**Comment by almindor** [comment] 2020-05-07 15:34
Could you please execute this from a terminal? (provided you have `curl` installed)

```bash
curl -X POST -k https://data.etherwall.com/api/init
```

and see what the result is?

**Comment by AJGierer** [comment] 2020-05-07 16:33
Curl in terminal --> `{"success":true,"version":"2.4.0","endpoint":"wss://linde.etherwall.com","nodes":1}Andrews-MacBook-Pro:~ andrewgierer$`

2.2.3 --> https://www.etherwall.com/downloads/ for the OSX image and "Download" link.

**Comment by almindor** [comment] 2020-05-07 16:40
> Curl in terminal --> `{"success":true,"version":"2.4.0","endpoint":"wss://linde.etherwall.com","nodes":1}Andrews-MacBook-Pro:~ andrewgierer$`
> 
> 2.2.3 --> https://www.etherwall.com/downloads/ for the OSX image and "Download" link.

That reply is correct. However the download link on the image on the site shows https://github.com/almindor/etherwall/releases/download/v2.4.0/macos_etherwall_2_4_0.dmg for me, so I'm a bit confused where v2.2 is coming from.

Could you please do one more call, do:
```bash
curl -X POST --data '{"currencies":["BTC","EUR","CAD","USD","GBP"],"version":2}' -k https://data.etherwall.com/api/currencies
```

If this works too then I'm a bit dumbfounded as to why you're getting invalid values inside EW.

**Comment by AJGierer** [comment] 2020-05-07 16:47
New curl --> `{"success":true,"currencies":{"Response":"Success","Message":"Do not take life too seriously. You will never get out of it alive.","Data":[{"Symbol":"BTC","Price":0.0215,"Open24Hour":0.02248,"LastUpdateTS":1588869616,"Volume24Hours":2297738,"Volume24HoursTo":50457.86},{"Symbol":"USD","Price":205.49,"Open24Hour":208.66,"LastUpdateTS":1588869615,"Volume24Hours":575928.2,"Volume24HoursTo":117865448},{"Symbol":"CAD","Price":286.8,"Open24Hour":295.41,"LastUpdateTS":1588869439,"Volume24Hours":3570.71777,"Volume24HoursTo":1034243.13},{"Symbol":"EUR","Price":190.28,"Open24Hour":193.09,"LastUpdateTS":1588869615,"Volume24Hours":147507.328,"Volume24HoursTo":28020222},{"Symbol":"GBP","Price":166.67,"Open24Hour":168.99,"LastUpdateTS":1588869580,"Volume24Hours":15627.25,"Volume24HoursTo":2601108.75}],"Type":100,"date":1588869617855}}`

Guessing this isn't good news for me :/ ?

For the link: Windows I'm seeing 2.4 in the link URL but for OSX I'm still seeing `https://github.com/almindor/etherwall/releases/download/v2.2.3/macos_etherwall_2_2_3.dmg` as the link URL.

**Comment by almindor** [comment] 2020-05-07 16:50
Hmm ok. For the download link I can't find out why that'd be the case, I even looked at the page source looking for `2.2` and only found one case with a javascript import unrelated to the download links. Can you try doing a "hard refresh" on the page? It seems like it's cached on your side for some reason. The old URL is "fine" tho no phishing :ok: 

For the error, it's odd. The downloads work fine for you directly, so not sure why you'd get a bad reply from within etherwall. Could you try running EW on another computer? (doesn't matter which OS). No need for moving accounts, just see if you get the same error on start...

**Comment by AJGierer** [comment] 2020-05-07 17:05
Link: Hard refresh and browser cache clear. Checked in Chrome and Safari, but I keep seeing the 2.2.3.dmg link for OSX. Popped it open on my phone too and that's also the 2.2.3.dmg link.

Error: I can try a new machine shortly.

**Comment by almindor** [comment] 2020-05-07 17:13
I just figured out the download link issue, it seems wordpress has some bug, if I'm logged in as admin of the page I see the new download links, but if I log out I see the v2.2.3 you mention. I'll try to fix that somehow. Thanks for bringing that to my attention.

**Comment by AJGierer** [comment] 2020-05-07 18:57
Link: Happy to help.
Error: Working on a separate machine! Sorry for the headache here but really appreciate your help! I'll keep poking around and see if I can figure it out (low hopes on that outcome).

**Comment by almindor** [comment] 2020-05-07 18:58
Thanks for the info. Is the other machine also a Mac? Just trying to pin it down.

**Comment by AJGierer** [comment] 2020-05-07 19:00
Also a Mac, yes. Took a few minutes to download and update whatever was needed but eventually everything came back to life just fine.

**Comment by almindor** [comment] 2020-05-07 19:01
Ok in that case check your DNS setup on the first mac. Same network? See if your hosts file `/ets/hosts` might contain something regarding etherwall.com somehow. Otherwise I don't know.

Also check what the etherwall.com and data.etherwall.com resolve to (it should be `46.4.116.220`)

**Comment by AJGierer** [comment] 2020-05-07 19:08
Same network and confirmed the DNS is the same, but beyond that, TBPH, that's a little over my head. If you're still curious and want to walk me through it then I'd be happy to help you explore deeper. But I'm satisfied with the second machine working for now, especially under the assumption the problem is local to my first machine.

**Comment by almindor** [comment] 2020-05-07 20:01
As long as you can move your funds around all is good I guess.

It's an odd occurence tho is the Mac perhaps a different OS version? I'm wondering if something changed "underneath" like an SSL/version issue or such.

**Comment by almindor** [comment] 2020-05-09 15:49
Going to close this issue. If you continue having Mac specific problems please create a new one as this one was meant for the server side problems.

**Closed by almindor** 2020-05-09 15:49 UTC
Labels: server issue
