### ISSUE TITLE
Transaction Issues

### ISSUE THREAD

**Issue by etherwallhelp** [almindor/etherwall#129] opened 2021-02-10 19:23 UTC
So multiple instances over the last few weeks I've got my payout into my Etherwall. After that I go to send tab and attempt to send it to a different market based wallet of mine. I put it all the prices, estimate the gas prices, everything on the page always looks correct. I hit send amount. Sometimes the amount will send. Other times it says i sent 0.0000 and only the gas price was paid. Each time I look carefully at the values, I've even reverted to checking your Gas price calculator on my own each time.

EVERY TIME THE INFO IS 100% CORRECT. Yet it's like a 25% chance it will actually send the amount requested and not just waste 5$ in gas fees. I appreciate you Etherwall, for my first month of mining after being intrigued for years, I already have made 80$ atleast in USD of eth, just to have 20$ of it wasted on bogus gas fees where it won't even send my coin. 

It is not user error, I've literally tried everything I can do, info stays the same. Sometimes it will send all my 0.02 or whatever, other times it says 0.000000 sent, gas price paid. Absolutely ridiculous.

**Comment by almindor** [comment] 2021-02-10 19:51
Would it be possible to provide the transaction hashes? I understand this might be touchy, but I'd have to look at something to begin.

Were these normal sends or contract executions?

**Comment by Azianpersuazian** [comment] 2021-02-21 01:34
Have you found a resolution to this? I am having the same issue.  I am inputing all the correct information and it is not sending. It creates a transaction hash ( 0x2fb7828af7742560608b1cfe75e7828b9b758edc636fc268d2fc3fa150ab94c7 ) but says invalid when I search it and the block# is 0.  I'm not sure what's going on but I need to get this Eth out ASAP!

**Comment by almindor** [comment] 2021-02-21 04:09
> Have you found a resolution to this? I am having the same issue. I am inputing all the correct information and it is not sending. It creates a transaction hash ( 0x2fb7828af7742560608b1cfe75e7828b9b758edc636fc268d2fc3fa150ab94c7 and tried it a second time 0x6b21170985830772e0ec312f26b9dd1d67b24a45abb740baffab3e4089ef73c4) but says invalid when I search it and the block# is 0. I'm not sure what's going on but I need to get this Eth out ASAP!

Hey. This transaction has is not on the network so it was never mined.

This can happen if the gas price goes up and the transaction gets dropped from the mempool.

I just checked the server and it seems the node is having issues. I'll be restarting it and try to provide an alternative via infura. If you really need this ASAP you can use an alternative client/website that accepts geth accounts.

**Comment by almindor** [comment] 2021-02-21 04:13
The infura server is up now. If you retry the transaction it should work. The reason it didn't was that the main etherwall server had an issue and was behind on sync causing low gas price to be used. This results in the transaction never getting mined.

**Comment by Azianpersuazian** [comment] 2021-02-21 04:18
Thank you.  Looks like I lost quite a bit with all those transactions that didn't go thru :( 

Just tried again. Hopefully it works - 0x954e201f2cf8769a8484a52e4258a417391257e877643cb9939ba041aa86aaf2 is the transaction hash.

**Comment by almindor** [comment] 2021-02-21 04:19
> Thank you. Looks like I lost quite a bit with all those transactions that didn't go thru :(
> 
> Just tried again. Hopefully it works - 0x954e201f2cf8769a8484a52e4258a417391257e877643cb9939ba041aa86aaf2 is the transaction hash.

What do you mean lost? As in "lost because of delays" or lost on transaction fees? Because you don't lose any fees on transactions that don't go through like this.

**Comment by almindor** [comment] 2021-02-21 04:23
Closing this as the server issue is worked-around and once the primary server catches up should be resolved there as well. I'll keep the backup infura node in the list to prevent these in the future and will be looking into adding some automated restarts to the primary node if it falls behind.

Sorry about any issues this might have caused.

**Comment by Azianpersuazian** [comment] 2021-02-21 04:26
Oh I def lost in transaction fees. I went from lost about .01 Eth. I have a bunch of blank transactions that showed up in the history from me trying multiple times and my wallet balance def went down.

**Comment by almindor** [comment] 2021-02-21 04:27
> Oh I def lost in transaction fees. I lost about .01 Eth. I have a bunch of blank transactions that showed up in the history from me trying multiple times and my wallet balance def went down.

This shouldn't be possible if they didn't register on the network. Can you please provide some of the hashes?

**Comment by Azianpersuazian** [comment] 2021-02-21 04:33
Soooooo they aren't in my history.  Then wtf happened to .01 of my eth? I had over .1 ETH to send (after transaction fees)  and I tried multiple times to send during those issues and this time I was only able to .09 (after transaction fees) WTF?

**Comment by almindor** [comment] 2021-02-21 04:37
> Soooooo they aren't in my history after closing out and reopening. Then wtf happened to .01 of my eth? I had over .1 ETH to send (after transaction fees) and I tried multiple times to send during those issues and this time I was only able to .09 (after transaction fees) WTF?
> 
> Edit: Oh well. I'm not going to sweat it.

You can check the full history of your account on etherscan. If it's the same one that worked in the end (the same "from") then you can check that here: https://etherscan.io/address/0xad41fda6c57cc2a65636c790a2efd1a87ba97df2

There is an odd 0 value transaction that did register ~12h ago here https://etherscan.io/tx/0xb1ebdd88952999cb3e5c816398df19a0c56952b2e9b548e9ae75880f57374057

Was this supposed to be > 0 in value?

**Comment by almindor** [comment] 2021-02-21 04:42
Re-opening the issue since the 0 value transactions on chain don't make sense. I suspect there might be another problem tied to the UI here if the server is behind/having issues. Perhaps it changes the value to 0 due to some sort of gas price race condition.

I'll have to dig deeper for that tho.

**Comment by Azianpersuazian** [comment] 2021-02-21 06:10
Ah, I did not know that. Thank you for that information.

No, I was attempting to send my Eth out but kept getting those errors.  I left a went to shopping hoping the issues would clear up, and I tried a few more times but kept getting the same error. I tried raising the gas prices by 10% and 20% but nothing worked.

**Comment by almindor** [comment] 2021-02-21 06:12
> Ah, I did not know that. Thank you for that information.
> 
> No, I was attempting to send my Eth out but kept getting those errors. I left a went to shopping hoping the issues would clear up, and I tried a few more times but kept getting the same error. I tried raising the gas prices by 10% and 20% but nothing worked.

Thanks for the info. I think the issue is some sort of gas price estimation race condition when the node is having problems. I'll try to simulate the conditions so I can reproduce locally.

**Comment by almindor** [comment] 2021-02-26 00:21
Fixed in latest master, I will release v3.0.2 sometime tomorrow.

**Closed by almindor** 2021-02-26 00:21 UTC
Labels: bug, question, server issue
