### ISSUE TITLE
ERROR IN TNX: OUT OF GAS - SEND ETH TO POLONIEX

### ISSUE THREAD

**Issue by Jarroduk** [almindor/etherwall#66] opened 2017-11-01 16:01 UTC
Hello,

I got the following error when sending to a poloniex account,
https://etherscan.io/address/0xc5eb29459dcda801d40ffa66af2ab973e75901c9

1) how do i get my coins back?
2) how do i work out how much gas to put to send to poloniex account?

Thanks in advance. :-)

**Comment by almindor** [comment] 2017-11-01 16:23
Hey.

Is the destination address a standard Poloniex "deposit" address?

This is a contract you sent to. It's not verified at Etherscan so I can't say what it's trying to do.
I haven't used Poloniex in a while, but will try later today to see if they maybe changed how their deposits work and use a "receiver" contract.

The estimate for gas is from Geth but it's a known issue in their code that sometimes the estimates seem to be done wrong. In this case the total number of gas consumed was 1410791 and the total fee you payed for this was 0.00027417600002 Ether ($0.08) according to Etherscan.

There's nothing you can do to get the $0.08 worth of ETH back I'm afraid, but the 0.49 ETH you were sending should've been sent back to you. If not then the contract might be fraudulent.

If I look at other transactions going to that contract I see they used 39512 GAS total. You can set GAS to whatever you want, any leftovers should go back.

I'd try sending with 90000 GAS but only if you're 100% sure about this destination address/contract!

If you can wait a bit I'll try and confirm that Poloniex is using an unverified contract for receives.

**Comment by almindor** [comment] 2017-11-01 16:24
NOTE: when changing the GAS value in the transaction dialog, do it at the end. Fill in all the other fields any only then change the GAS value otherwise it might get overridden with the estimate again.

**Comment by almindor** [comment] 2017-11-01 16:43
So I went to my Poloniex account and went to the deposit tab/eth. The address they gave me is `0x4eE8DE1d0b2B6cD1848f5b356fAb6de546edA6A6` which is a normal address, not a contract. I wouldn't expect them to use a contract directly because that's risky if users do something strange or use e.g. another exchange to send from.

Are you sure the to address you're using is legit?

**Comment by almindor** [comment] 2017-11-01 16:50
When it comes to the estimate being wrong this is actually a bug in Etherwall fixed in master tho.

You can test by putting the `0xc5Eb29459dCdA801d40fFA66af2Ab973e75901c9` address in the "to" and filling the rest. If you leave value at 0 your estimate is going to be low (still ok with 0 value tho!). If you change the value it stays at 0 but if you press "estimate" with value > 0 it'll change to the right amount of 39512.

So if you trust the destination just press estimate before send :)

Version 2.1.0 is around the corner, will be released soon fixing this and adding ERC20 (token) support.

I'm going to close this issue since its root cause is fixed in maste/trunk.

NOTE: if you didn't get your 0.49 ETH back from that contract contact Poloniex and ask them about it. Mention you sent with too low gas value.

**Closed by almindor** 2017-11-01 16:50 UTC
Labels: question

**Comment by Jarroduk** [comment] 2017-11-01 17:07
Hello, 

First thank you for the speedy response I really appreciate that, the coins have not been returned to my wallet, do you know if there is some sort of time frame for the coins to come back? 

I will next time try the amount you have stated for the gas, this is the first time I have sent from my wallet to Poloniex. 

Is there anything that can be done to get my coins back?

Thanks 
Jarrod

**Comment by almindor** [comment] 2017-11-01 17:10
So this is an out of gas error which means by default the contract should've sent the remaining 0.49 ETH back to your account.

Looking at your address I see it has balance of `0.491250855367916721 Ether` which seems correct.

Is Etherwall not showing that balance? Are you using Thin client or not?

NOTE: your ETH (the 0.49) is definitely back in the `0xD8e90B88FC086e118491B491F93b6E3149476F5d` address. You can see that on etherwall [here](https://etherscan.io/address/0xd8e90b88fc086e118491b491f93b6e3149476f5d)

**Comment by almindor** [comment] 2017-11-01 17:17
NOTE: sent you `0.000274176000000000` ETH back to pay for that TX out of gas loss as it was caused by a bug in Etherwall.

**Comment by Jarroduk** [comment] 2017-11-01 19:08
Hello, 

Yes I can now see the balance and thanks for send me the gas charge, I really do appreciate your help and your speedy response.

Thanks
Jarrod
