### ISSUE TITLE
etherwall 2.2.3 problems

### ISSUE THREAD

**Issue by alphaferret** [almindor/etherwall#107] opened 2018-07-14 13:16 UTC
message on startup: invalid params:invalid index:invalid digit found in string.

trying to send transaction it hangs. mouse over send button shows invalid receiver address

but receiver address shows up fine in etherscan

also getting 'error on socket:unknown error' on the transaction send page

please fix this asap

**Comment by almindor** [comment] 2018-07-14 15:05
Which OS/version are you on?

**Comment by alphaferret** [comment] 2018-07-14 15:40
linux. i was able to complete a transaction. i closed the app a few times after each time it was hanging and then it worked. not sure about future transactions though.

**Comment by almindor** [comment] 2018-07-14 19:20
Is this Arch linux? The package maintainer there made a mistake and didn't update the ew-node subproject when building. I reported this over a month ago but he's taking his sweet time.

You can build from source yourself but you'll need to make sure to use the right ew-node version (git submodule update).

The issue is [on the arch issue tracker here](https://bugs.archlinux.org/task/59043?project=5&string=etherwall).

You can also use the diff I put there to use abs to build the package.

**Comment by alphaferret** [comment] 2018-07-20 09:00
makepkg using your diff pkgbuild gave this error:

==> ERROR: etherwall.desktop was not found in the build directory and is not a URL.

**Comment by almindor** [comment] 2018-07-21 21:51
Indeed, the main issue is I can't do anything else but report and wait :(

I had full control when it was in the AUR but since it got "upgraded" to community repo someone else is the maintainer.

Glad you could get it to work tho :) Will keep the issue open until the package gets fixed in arch.

**Comment by UGatgithub** [comment] 2019-03-17 12:22
Have a similar issue for the light client under Windows 10 where I get:
bail[hard]: WS: Disconnected from websocket
WS: Disconnected from websocket
bail[hard]: WS: Unbekannter Fehler
WS: Unbekannter Fehler
bail[hard]: WS: Unbekannter Fehler
WS: Unbekannter Fehler
bail[hard]: Invalid params: expected a hex-encoded hash with 0x prefix.
Received: {"jsonrpc":"2.0","error":{"code":-32602,"message":"Invalid params: expected a hex-encoded hash with 0x prefix."},"id":18}
Sent: {"id":18,"jsonrpc":"2.0","method":"eth_getTransactionByHash","params":["05112f62832bf9a0f05c12e2ef08ac2fff5dbb672599f8c8964d263d2e318290"]}
Received: {"jsonrpc":"2.0","result":"0x0","id":17}
Sent: {"id":17,"jsonrpc":"2.0","method":"eth_getTransactionCount","params":["0x004adA05E434e87b70fE046012F486C00EB03500","latest"]}
Received: {"jsonrpc":"2.0","result":"0x0","id":16}
...

**Comment by almindor** [comment] 2019-03-17 14:38
Light client isn't supported. It's odd that there's a 0x-less request tho.

**Comment by almindor** [comment] 2019-04-01 22:45
This should now be fixed in `2.3.2`, reopen if not so.

**Closed by almindor** 2019-04-01 22:45 UTC
Labels: bug
