### ISSUE TITLE
Bad gateway 502

### ISSUE THREAD

**Issue by chatov77** [almindor/etherwall#93] opened 2018-05-16 12:59 UTC
Hello i can´t open my etherwall wallet i have this log message:
![image](https://user-images.githubusercontent.com/39337529/40118247-49d11a26-5911-11e8-872f-417059b65efb.png)

**Comment by almindor** [comment] 2018-05-19 02:09
Duplicate of #91

**Closed by almindor** 2018-05-19 02:09 UTC
Labels: duplicate
