### ISSUE TITLE
no transaction entry after block #2414692

### ISSUE THREAD

**Issue by SnaiLiuS** [almindor/etherwall#18] opened 2017-01-16 20:01 UTC
I cant see any transactions after block #2414692 in transaction history tab.

**Comment by almindor** [comment] 2017-01-17 00:00
Thanks for reporting. The issue is my small 4GB RAM server cannot handle geth and/or parity anymore. This is due to the DOS attacks done a few months ago on ethereum. Neither geth nor parity are able to sync up anymore on a machine with such low amount of RAM so I can't keep my DB updated.

I will keep trying as they fix more issues and remove more clutter from the blockchain.

This issue will remain open until then.

**Comment by SnaiLiuS** [comment] 2017-01-17 00:42
can it be done from local machine blockchain (without geth fast sync)?

**Comment by almindor** [comment] 2017-01-17 01:30
No, the issue is there is no API call that would return the list of transactions for an account. I dug a bit more into their code and the actual problem is sadly how they store the blockchain data (at least in geth).

It's using a basic key/value pair document "DB" called LevelDB which has very limited support for indexing etc.

So even if they wanted to add the API they can't do that easily. There's an open issue on go-ethereum about it.

That's why I made a Postgres DB with node.js client that sucks all the data out of each block on my server and puts it in the DB. I could do a simple select to get transactions for accounts this way.

**Comment by almindor** [comment] 2017-01-17 01:34
Updated my server to use parity 1.4.9, will give it another try and see if it syncs past the troublesome blocks.

**Comment by SnaiLiuS** [comment] 2017-01-17 03:13
any external solution, like etherscan.io?

**Comment by almindor** [comment] 2017-01-26 05:58
Managed to get parity 1.5.0 working past the troublesome blocks, my DB is now catching up and should have new data by tomorrow.

**Comment by almindor** [comment] 2017-03-14 02:31
Closing as this should be fixed, please re-open if you still don't see your transactions

**Closed by almindor** 2017-03-14 02:31 UTC
