### ISSUE TITLE
Error at start: "bail[hard]: Invalid params: Invalid index: invalid digit found in string." 

### ISSUE THREAD

**Issue by aleixpol** [almindor/etherwall#108] opened 2018-07-24 23:28 UTC
Only tried to configure it, it showed that message box first thing:

Here's the log:
```
bail[hard]: WS: Disconnected from websocket
WS: Disconnected from websocket
bail[hard]: WS: Unknown error
WS: Unknown error
bail[hard]: WS: Unknown error
WS: Unknown error
bail[hard]: Invalid params: Invalid index: invalid digit found in string.
IPC ready, initializing poller
Connected to IPC socket
Connecting to IPC socket /home/apol/.ethereum/geth.ipc
Geth starting /usr/bin/geth --syncmode=fast --cache 512 --datadir /home/apol/.ethereum --nousb --maxpeers=0 --nodiscover --nat=none
Connected to WS endpoint
Checking to see if there is an already running geth...
Etherwall starting
Connecting to WS endpoint: wss://linde.etherwall.com
Connecting to main Etherwall server
```

**Comment by almindor** [comment] 2018-07-25 15:06
Hey, this is on Arch linux correct? If so this is a duplicate of #107 see details there. I'm afraid I can't do much until the package maintainer fixes their error. A workaround is discussed in the issue there as well.

If this is not arch please re-open.

**Closed by almindor** 2018-07-25 15:06 UTC

**Comment by aleixpol** [comment] 2018-07-25 17:51
Correct, that's arch, will follow up there. Thanks!
