### ISSUE TITLE
Etherwall 2.2.1 on Mac OS X 10.13.4 not working with Trezor...

### ISSUE THREAD

**Issue by Mr-Beetroot** [almindor/etherwall#90] opened 2018-05-04 04:09 UTC
Greetings,

There is an issue with Etherwall 2.2.1 on Mac OS X 10.13.4 used with Trezor

For some reason, Etherwall does not sign transactions confirmed to be sent via Trezor, i.e the password entry prompt is not activated and the application freezes after the "send" button is clicked in Etherwall 2.2.1

This issue has not been fixed for a few months already
Please look into this soon

Regards,
Dennis

**Comment by almindor** [comment] 2018-05-04 16:05
Hey, thanks for reporting. I'll try to reproduce on my mac. In the meantime could you please try running Etherwall from the commandline and see if when you try to send it writes anything in the terminal?

You can switch to using testnet to not risk spending any real ether.

**Comment by almindor** [comment] 2018-05-08 01:10
I think I was able to reproduce the issue. It seems for some reason the "import trezor addresses" dialog pops up "behind" the send dialog and takes over focus causing a "freeze" where nothing can be done but killing the application.

Will investigate further.

**Comment by almindor** [comment] 2018-05-08 01:29
I see, sorry a bit of a red herring there. Seems I used a different TREZOR device for my old mac tests but it did point in the right direction. Still confirm the deviceID match for me please.

The issue is because of how MacOS X handles modal dialogs. If the "send" dialog is open and TREZOR received a send command it tries to open a new modal dialog on top with the PIN pad. That dialog however somehow shows "behind" the send dialog and blocks everything.

I'll hack a workaround for this mac/qt bug for the time being using nonmodal settings. Should have a release out soon.

**Comment by almindor** [comment] 2018-05-08 04:38
Should now be fixed in v2.2.2. Re-open if issue still persists.

**Closed by almindor** 2018-05-08 04:38 UTC
Labels: bug
