### ISSUE TITLE
Repeated every 5 minutes: Response parse error: Ungültiger Wert

### ISSUE THREAD

**Issue by UGatgithub** [almindor/etherwall#37] opened 2017-08-04 18:17 UTC
The Application running on a Windows 10 PC returns exactly every 5 Minutes this output:

Response parse error: Ungültiger Wert

and seldom I see there is an additional HTTP Response parse error: Ungültiger Wert

Using Debug mode I found the following, so I guess the issue relates to non responsive currency value load trials during blockchain sync.

Response parse error: Ungültiger Wert
HTTP Post reply: 
HTTP Post request: {
    "currencies": [
        "BTC",
        "EUR",
        "CAD",
        "USD",
        "GBP"
    ],
    "version": 2
}

How can I fix this issue?

**Comment by almindor** [comment] 2017-08-04 18:39
Hmm invalid value. Do you see this as an error popup? Can you please look into the logs, copy them to clipboard and paste here as file or code block?

You're not using a custom geth correct?

**Comment by UGatgithub** [comment] 2017-08-04 18:41
No I use the latest geth in C:/Users/myprofile/AppData/Roaming/Ethereum Wallet/binaries/Geth/unpacked/geth.exe

**Comment by UGatgithub** [comment] 2017-08-04 19:31
I found the Currencies page mostly gets loaded with values when I start the Application but from time to time the values are gone and only the 1 plus the Ether symbol stays visible. I think its connected to the bug.

**Comment by almindor** [comment] 2017-08-04 19:48
Hmm well it could also be geth, will try with latest. I don't see the error or currencies issue on my end.

**Comment by UGatgithub** [comment] 2017-08-04 20:08
Well, my laptop is connected via WLAN and the sync update takes quite long, maybe network speed is a reason why I get the issue and you don't?!? Do you request the currency values every 5 minutes?

**Comment by almindor** [comment] 2017-08-04 20:22
Ah good to know I thought you were running in "thin client mode".

The currencies are queried every 5 minutes but there's also a server-side mechanism with a cache.

Can you enable debug logging (in the log, switch to DEBUG) and wait for the error? Copy the log to file and put here.

Thanks

**Comment by UGatgithub** [comment] 2017-08-04 20:44
There's nothing more then this in the debug log at the time of the error.

Response parse error: Ungültiger Wert
HTTP Post reply:
HTTP Post request: {
"currencies": [
"BTC",
"EUR",
"CAD",
"USD",
"GBP"
],
"version": 2
}

**Comment by almindor** [comment] 2017-08-04 21:39
hmm ok so that seems like you're getting an empty reply. I assume you're running latest etherwall version 2.0.1 correct?

Mine seems to work fine and the prices show up too so not sure. Is it possible there's a networking problem? Are you connected to the internet directly or do you use any proxying?

**Comment by UGatgithub** [comment] 2017-08-04 22:04
Yes, latest etherwall and no proxying, connected by WLAN via the router (FritzBox) to Internet. Could it be a firewall (or anti virus) related issue then?

**Comment by almindor** [comment] 2017-08-04 22:09
Do you consistently get empty responses logged like this evey time there's a request? If so then possibly as it does work from my computer.

Did the currencies ever show up with prices in the list? If it's intermittent then I'm not sure what to do about it as it could be anything.

**Comment by UGatgithub** [comment] 2017-08-04 22:21
Sometimes they load when I start the Application, sometimes not but during sync the issue appears regularly every 5 minutes. I can do a test with disabled firewall or is there a specific firewall setting to check?

**Comment by almindor** [comment] 2017-08-04 22:26
You can try disabling just for a few minutes and restart Etherwall. See if things hold up. Note that disabling firewall on windows is risky so only do it if you what you're doing as viruses could find a way in without ports blocked. If you're on latest windows and updated fully you should be ok tho.

What makes this hard to debug is that there's no reply, an empty body. This usually means one of two things. A network/firewall issue, or a server issue where the request got rejected. I checked the server, seems to be working fine and as I said I get latest prices ok.

If you're willing I can build a special debug version of Etherwall (for windows) with extra logging to see return code of that request. That should give us more info. I'll try and build it tomorrow and paste a link here.

**Comment by UGatgithub** [comment] 2017-08-04 23:18
OK, I can give it a trial tomorrow then.

**Comment by almindor** [comment] 2017-08-05 06:06
Here's the modified executable. Note: you need to copy over to your Etherwall folder and run the `Etherwall_debug.exe` instead of the normal one.

[etherwall_debug.zip](https://github.com/almindor/etherwall/files/1202152/etherwall_debug.zip)

You can set your logs back to info only as I added explicit logging for reply status in this version. You should see it in the logs. Please paste the line here. Thanks!

**Comment by UGatgithub** [comment] 2017-08-05 09:03
Thank you Aleš,
I ran the debug version multiple times with Firewall enabled now and got no error, so I will use it during the next days and let you know when the issue reappears.

By now I got the following output which I crosschecked with the normal etherwall.exe and debug mode and found the complete reply there, so the Parse error can't be reproduced this morning.

HTTP currencies reply status: 200  (repeats every 5 minutes)
HTTP currencies reply status: 200
HTTP currencies reply status: 200
Restored 1 transactions from etherdata server
Connected to IPC socket
HTTP currencies reply status: 200
Connecting to IPC socket \\.\pipe\geth.ipc
Geth starting C:/Users/myprofile/AppData/Roaming/Ethereum Wallet/binaries/Geth/unpacked/geth.exe --syncmode=fast --cache=1024 --maxpeers=24 --datadir C:/Users/myprofile/AppData/Roaming/Ethereum Wallet
Checking to see if there is an already running geth...
Etherwall starting

**Comment by almindor** [comment] 2017-08-05 10:08
Helper currency is used when sending transactions to show fees/gas price in so people can easily gauge how much "actual value" their transactions cost.

**Comment by UGatgithub** [comment] 2017-08-05 11:08
Got it again ....

DEBUG
...
Response parse error: Ungültiger Wert
HTTP Post reply: 
HTTP currencies reply status: 
HTTP Post request: {
    "currencies": [
        "BTC",
        "EUR",
        "CAD",
        "USD",
        "GBP"
    ],
    "version": 2
}

INFO
...
Received: {"jsonrpc":"2.0","id":759,"result":"0x5"}
Sent: {"id":759,"jsonrpc":"2.0","method":"net_peerCount","params":[]}
Response parse error: Ungültiger Wert
HTTP currencies reply status: 
Response parse error: Ungültiger Wert
HTTP currencies reply status: 
HTTP currencies reply status: 200
HTTP currencies reply status: 200
HTTP currencies reply status: 200
HTTP currencies reply status: 200
Connected to IPC socket
Connecting to IPC socket \\.\pipe\geth.ipc
Geth starting C:/Users/myprofile/AppData/Roaming/Ethereum Wallet/binaries/Geth/unpacked/geth.exe --syncmode=fast --cache=1024 --maxpeers=24 --datadir C:/Users/myprofile/AppData/Roaming/Ethereum Wallet
HTTP currencies reply status: 200
Checking to see if there is an already running geth...
Etherwall starting

**Comment by almindor** [comment] 2017-08-05 18:25
Hmm so when it errors out even the status is unknown. This seems like a networking issue I'm afraid. Not sure what else to try as noone else reported this I'm almost sure now the issue is on your end.

It's also very intermittent. Can you maybe leave it going for a while and see if it has a "pattern"? E.g. how often it fails, in what intervals.

**Comment by UGatgithub** [comment] 2017-08-05 21:58
Once it starts to fail it continues, have not seen it working again then before restarting etherwall but maybe it does. I will use the debug version for a while and check on a possible pattern. Can also try if it appears when I use an ethernet cable. Keep you updated. Thanks for your support!

**Comment by wujomasta** [comment] 2017-08-08 12:28
hello, is it only for eth and btc? 
how to transfer my btc into this wallet? I hold it on localbitcoins.co.uk

**Comment by UGatgithub** [comment] 2017-08-08 18:48
you create a wallet address in this wallet and send your bitcoin to that.

**Comment by wujomasta** [comment] 2017-08-08 19:00
So if i have adress for etc and i already purchased sucsesfully this
currency i use the same address to send btc?

**Comment by almindor** [comment] 2017-08-08 19:15
Etherwall is `ETH ONLY!` Please don't try to send ETC or BTC or anything else but ETH to it!

BTC shouldn't even work as the addresses are different. If you did send ETC to a Etherwall generated ETH address there's a way to get to it tho, but ETC is NOT supported by Etherwall.

**Comment by almindor** [comment] 2017-08-08 19:16
@UGatgithub I'm closing this issue now, if you think you found something that's a problem on etherwall's side as opposed to network on your end re-open.

Thanks

**Closed by almindor** 2017-08-08 19:16 UTC
Labels: bug

**Comment by wujomasta** [comment] 2017-08-08 19:34
O mean ETH, to did it sucsessfull,
Thx

**Comment by UGatgithub** [comment] 2017-08-13 18:26
Any idea how you could add a manual refresh or so to overcome the issue?

![currency issue](https://user-images.githubusercontent.com/30733304/29252362-96bb8216-8065-11e7-95ab-4e77058852e1.jpg)

**Comment by wujomasta** [comment] 2017-08-14 08:16
HI

I tried to sent eth to my bittrex and i receive this "Address checksum
mismatch. Use only properly checksumed addresses to prevent wrong sends."

I did the same with localbitcoin and i receive btc in 2 minutes

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-08-13 19:26 GMT+01:00 UGatgithub <notifications@github.com>:

**Comment by almindor** [comment] 2017-08-14 08:53
@wujomasta can you please open a new issue for this? It's getting very confusing in this bugrep.
