### ISSUE TITLE
Mac OS Sierra - app window not visible

### ISSUE THREAD

**Issue by dkanas** [almindor/etherwall#20] opened 2017-05-23 14:10 UTC
I downloaded and installed Etherwall, then I ran it and the icon appears in the dock, but there's no app window visible. I tried redownloading and reinstalling, but it didn't help. Any idea what might be wrong or how could I debug it?

**Comment by almindor** [comment] 2017-05-24 13:50
I'm aware of this issue, but can't reproduce on my mac books. One of my friends reported the same but he didn't get any error indication. I'm going to try and compare the plugins and libraries packed together in the older versions of .app to see if something went missing.

Do you know if any older version of etherwall worked ok for you?

**Comment by almindor** [comment] 2017-05-24 14:20
I changed one bit that might be related, can you try downloading from http://download.etherwall.com/etherwall_test.dmg and see if that starts up?

**Comment by dkanas** [comment] 2017-05-24 18:45
Unfortunately it was the first version I was using on a Mac, downloading the test version, I will let you know in a moment

**Comment by dkanas** [comment] 2017-05-24 18:53
The test version behaves the same, I looked into the mac console, maybe those info can help somehow
<img width="1220" alt="zrzut ekranu 2017-05-24 o 20 52 39" src="https://cloud.githubusercontent.com/assets/17471851/26420509/0ecfcb14-40c3-11e7-92bc-73820258e201.png">

**Comment by almindor** [comment] 2017-05-24 20:22
Can you please provide your exact mac os x version?

**Comment by dkanas** [comment] 2017-05-24 20:23
It's 10.12.4

**Comment by almindor** [comment] 2017-05-24 20:29
Hmm the errors in that log all point to things that should've been fixed in mac os x 10.12.2+ so not sure where else to look. Nothing in there really goes into app logic, I think this is some sort of QT5/mac issue. I have two mac book pros on version 10.12.4 and get no such errors on either of them.

Not sure where else to look here. Are you able to try and compile/run etherwall from source using Qt5/QtCreator?

NOTE: if so please use Qt version 5.7.x at highest as 5.8 has other issues that prevent etherwall from working.

**Comment by dkanas** [comment] 2017-05-24 20:43
I will try to do it when I will have some more free time, I just updated to 10.12.5, but it also didn't help

**Comment by almindor** [comment] 2017-05-27 19:55
Can you also try running an older version for example: [1.3.0](https://downloads.etherwall.com/etherwall_1_3_0.dmg)

See if the older versions still work for you.

**Comment by dkanas** [comment] 2017-05-28 11:21
1.3.0 works for me :)

**Comment by almindor** [comment] 2017-05-28 12:56
Cool, I think it might be qt5.7+ maybe they broke something in the `macdeployqt` tool.

Can you please try [this test version?](https://downloads.etherwall.com/etherwall_test2.dmg)

**Comment by dkanas** [comment] 2017-05-28 13:07
The app loads up, but there is a problem with geth (probably also on the 1.3.0 version, because I got an error there, too)
<img width="886" alt="zrzut ekranu 2017-05-28 o 15 05 20" src="https://cloud.githubusercontent.com/assets/17471851/26528971/4d4105c4-43b7-11e7-9b03-9005b569710e.png">

**Comment by almindor** [comment] 2017-05-28 13:22
Ah good to know, This version used geth 1.6.1 and the 1.3.0 version used some old geth which would explain these.

Can you please try redownloading latest from the webpage again? I repackaged 1.4.9 with Qt5.6 which should hopefully have fixed the issue now. If it did please close this thread. Thanks

SHA256 sum should be `df2c9dcada47f18ec877385ce7f33d4571a470db62feab6d80ae49c9eece479d`

**Comment by dkanas** [comment] 2017-05-28 14:31
It starts, but the problem with geth is still there. It does work when I start up the geth from homebrew first though.
<img width="877" alt="zrzut ekranu 2017-05-28 o 16 29 13" src="https://cloud.githubusercontent.com/assets/17471851/26529604/0c35860c-43c3-11e7-9ac5-e60a8f9744a2.png">

**Comment by almindor** [comment] 2017-05-28 15:45
Hmm interesting, I wonder if there's an actual binary incompatibility between our macs then. The geth packaged with etherwall is 1.5.9 from homebrew.

For a workaround you can change your geth path in etherwall settings to point to `/usr/local/bin/geth` or wherever else you might have a "native" geth binary.

I've opened a new issue #21 you can monitor that there. I'll close this one as the qt5/plugin problems are now fixed.

**Closed by almindor** 2017-05-28 15:45 UTC

**Comment by almindor** [comment] 2017-05-28 15:52
Actually if you're still getting notifications here, can you send me your geth version that worked for you? I want to see if there's a difference.

**Comment by dkanas** [comment] 2017-05-28 16:04
here's the output of `geth version`

```Geth
Version: 1.6.1-stable
Git Commit: 021c3c281629baf2eae967dc2f0a7532ddfdc1fb
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.8.1
Operating System: darwin
GOPATH=/Users/user/go
GOROOT=/usr/local/Cellar/go/1.8.1/libexec
```
