### ISSUE TITLE
conecting to node

### ISSUE THREAD

**Issue by franjcast** [almindor/etherwall#92] opened 2018-05-15 16:04 UTC
hi my etherwall is Not working.. i cant see my accounts... cant connect to nodes on thin client.. but when turn off thin client and restar app, i See the accounts with 0 balances and the app is syncronizing blocks..

logs
application
Connected to IPC socket
Connecting to IPC socket \\.\pipe\geth.ipc
Geth starting C:/Users/francisco/Downloads/win32_etherwall_2_2_2/Etherwall/geth.exe --syncmode=fast --cache 512 --datadir C:/Users/francisco/AppData/Roaming/Ethereum --nousb --maxpeers=0 --nodiscover --nat=none
Checking to see if there is an already running geth...
Etherwall starting
Response error: unknown error
HTTP Response parse error: illegal value
Response parse error: illegal value
Response error: unknown error
HTTP Response parse error: illegal value
Connecting to main Etherwall server

geth
INFO [05-15|12:02:38] Finished upgrading chain index           type=bloombits

INFO [05-15|12:02:34] Upgrading chain index                    type=bloombits percentage=98

INFO [05-15|12:02:25] Regenerated local transaction journal    transactions=0 accounts=0
INFO [05-15|12:02:25] Starting P2P networking 
INFO [05-15|12:02:25] IPC endpoint opened                      url=\\\\.\\pipe\\geth.ipc
INFO [05-15|12:02:25] RLPx listener up                         self="enode://4aab29b5a3f890b30c48dcf1fdbd2f4f1d40fd4e5630bddfa10ced025abc8de43cd90be6a16049058e8b707d73a2c349618e908702fe82db8a1e54425a062d1b@[::]:30303?discport=0"

INFO [05-15|12:02:25] Loaded local transaction journal         transactions=0 dropped=0
INFO [05-15|12:02:25] Upgrading chain index                    type=bloombits percentage=94

INFO [05-15|12:02:25] Loaded most recent local fast block      number=1443069 hash=342281…5ed729 td=16924960947890295796

INFO [05-15|12:02:25] Loaded most recent local full block      number=0       hash=d4e567…cb8fa3 td=17179869184

INFO [05-15|12:02:25] Loaded most recent local header          number=1446728 hash=50ea96…20530e td=17045570793583738530

INFO [05-15|12:02:25] Initialised chain configuration          config="{ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Constantinople: <nil> Engine: ethash}"
INFO [05-15|12:02:25] Disk storage enabled for ethash caches   dir=C:\\Users\\francisco\\AppData\\Roaming\\Ethereum\\geth\\ethash count=3
INFO [05-15|12:02:25] Disk storage enabled for ethash DAGs     dir=C:\\Users\\francisco\\AppData\\Ethash                          count=2
INFO [05-15|12:02:25] Initialising Ethereum protocol           versions="[63 62]" network=1

INFO [05-15|12:02:18] Allocated cache and file handles         database=C:\\Users\\francisco\\AppData\\Roaming\\Ethereum\\geth\\chaindata cache=384 handles=1024

INFO [05-15|12:02:18] Starting peer-to-peer node               instance=Geth/v1.8.7-stable-66432f38/windows-386/go1.10.1

INFO [05-15|12:02:18] Maximum peer count                       ETH=0 LES=0 total=0

**Comment by resplendenteye** [comment] 2018-05-17 20:55
I am having the same issue.

**Comment by almindor** [comment] 2018-05-19 02:08
Duplicate of #91

**Closed by almindor** 2018-05-19 02:08 UTC
Labels: duplicate
